#!/usr/bin/env python3
"""Link temperature-OOD ensemble dispersion to extrapolative binodal error."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import spearmanr

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from experiments.run_all import COLORS, binary_parameters, nrtl_predict, save_figure  # noqa: E402
from src.thermo import PairPotentialSpec, canonical_embeddings, ideal_mixing_energy, lower_convex_hull_binodal, pair_potential_predict  # noqa: E402

RESULTS = ROOT / "results"
SECTIONS = ROOT / "sections"


def main():
    archive = np.load(RESULTS / "uncertainty_revision.npz")
    parameters = archive["parameters"]
    spec = PairPotentialSpec(canonical_embeddings(2), hidden_units=12, temperature_center=370.0, temperature_scale=80.0)
    temperatures = np.linspace(390.0, 450.0, 16)
    x1 = np.linspace(0.001, 0.999, 10400)
    x = np.column_stack([x1, 1.0 - x1])
    rows = []
    for temperature in temperatures:
        t = np.full(len(x), temperature)
        reference = lower_convex_hull_binodal(x1, ideal_mixing_energy(x) + nrtl_predict(x, t, binary_parameters())[0])
        member_endpoints = []
        for member in parameters:
            endpoint = lower_convex_hull_binodal(x1, ideal_mixing_energy(x) + pair_potential_predict(member, spec, x, t)[0])
            if endpoint is not None:
                member_endpoints.append(endpoint)
        if reference is None or len(member_endpoints) < len(parameters):
            continue
        member_endpoints = np.asarray(member_endpoints)
        mean = np.mean(member_endpoints, axis=0)
        standard_deviation = np.std(member_endpoints, axis=0, ddof=1)
        rows.append(
            {
                "temperature_K": float(temperature),
                "reference": list(reference),
                "ensemble_mean": mean.tolist(),
                "ensemble_std": standard_deviation.tolist(),
                "absolute_error": np.abs(mean - reference).tolist(),
            }
        )
    errors = np.array([row["absolute_error"] for row in rows]).ravel()
    uncertainty = np.array([row["ensemble_std"] for row in rows]).ravel()
    correlation = spearmanr(uncertainty, errors)
    payload = {
        "training_temperature_max_K": 370.0,
        "evaluation_temperature_K": [390.0, 450.0],
        "ensemble_size": int(len(parameters)),
        "grid_size": int(len(x1)),
        "isotherms": len(rows),
        "endpoint_mae": float(np.mean(errors)),
        "endpoint_max": float(np.max(errors)),
        "endpoint_uncertainty_error_spearman_rho": float(correlation.statistic),
        "endpoint_uncertainty_error_spearman_pvalue": float(correlation.pvalue),
        "rows": rows,
    }
    mae_exponent = int(np.floor(np.log10(payload["endpoint_mae"])))
    mae_mantissa = payload["endpoint_mae"] / 10**mae_exponent
    max_exponent = int(np.floor(np.log10(payload["endpoint_max"])))
    max_mantissa = payload["endpoint_max"] / 10**max_exponent
    (RESULTS / "extrapolative_binodal.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    (SECTIONS / "extrapolative_macros.tex").write_text(
        "% Auto-generated by experiments/run_extrapolative_binodal.py.\n"
        + rf"\newcommand{{\ExtrapBinodalMAE}}{{${mae_mantissa:.2f}\times 10^{{{mae_exponent}}}$}}" + "\n"
        + rf"\newcommand{{\ExtrapBinodalMax}}{{${max_mantissa:.2f}\times 10^{{{max_exponent}}}$}}" + "\n"
        + rf"\newcommand{{\ExtrapBinodalRho}}{{{payload['endpoint_uncertainty_error_spearman_rho']:.3f}}}" + "\n",
        encoding="utf-8",
    )

    reference = np.array([row["reference"] for row in rows])
    mean = np.array([row["ensemble_mean"] for row in rows])
    standard_deviation = np.array([row["ensemble_std"] for row in rows])
    fig, axes = plt.subplots(1, 2, figsize=(7.1, 2.9))
    for branch in (0, 1):
        axes[0].plot(reference[:, branch], temperatures[: len(rows)], color=COLORS["reference"], label="NRTL reference" if branch == 0 else None)
        axes[0].plot(mean[:, branch], temperatures[: len(rows)], "--", color=COLORS["potential"], label="Ensemble mean" if branch == 0 else None)
        axes[0].fill_betweenx(temperatures[: len(rows)], mean[:, branch] - 1.96 * standard_deviation[:, branch], mean[:, branch] + 1.96 * standard_deviation[:, branch], color=COLORS["uncertainty"], alpha=0.18)
    axes[0].set_xlabel(r"Mole fraction $x_1$")
    axes[0].set_ylabel("Temperature (K)")
    axes[0].set_title("(a) Binodal beyond 370 K training limit")
    axes[0].legend(frameon=False)
    axes[1].scatter(uncertainty, errors, color=COLORS["uncertainty"], alpha=0.75)
    axes[1].set_xscale("log")
    axes[1].set_yscale("log")
    axes[1].set_xlabel("Endpoint ensemble standard deviation")
    axes[1].set_ylabel("Absolute endpoint error")
    axes[1].set_title(rf"(b) Endpoint ranking: $\rho={correlation.statistic:.3f}$")
    fig.tight_layout()
    save_figure(fig, "fig12_extrapolative_binodal")
    print(json.dumps({key: payload[key] for key in payload if key != "rows"}, indent=2))


if __name__ == "__main__":
    main()
